# Generated by Django 6.0 on 2025-12-04 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nom d'utilisateur"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="Prénom"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="Nom"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Administrateur"),
                            ("library_admin", "Administrateur Bibliothèque"),
                            ("reader", "Lecteur"),
                        ],
                        default="reader",
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("is_staff", models.BooleanField(default=False, verbose_name="Staff")),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="users/avatars/%Y/%m/",
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le numéro de téléphone doit être au format: +999999999",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adresse"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, verbose_name="Pays"),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("suspended", "Suspendu"),
                            ("expired", "Expiré"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut abonnement",
                    ),
                ),
                (
                    "subscription_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin d'abonnement"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "ordering": ["-date_joined"],
                "indexes": [
                    models.Index(fields=["email"], name="users_custo_email_c80f75_idx"),
                    models.Index(
                        fields=["username"], name="users_custo_usernam_a8ad03_idx"
                    ),
                    models.Index(fields=["role"], name="users_custo_role_6a37b1_idx"),
                ],
            },
        ),
    ]
