# Generated by Django 6.0 on 2025-12-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="preferred_language",
            field=models.CharField(
                choices=[("fr", "Français"), ("en", "English"), ("ar", "العربية")],
                default="fr",
                max_length=5,
                verbose_name="Langue préférée",
            ),
        ),
    ]
