# Generated by Django 6.0 on 2026-01-20 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_phone_verified",
            field=models.BooleanField(default=False, verbose_name="Téléphone vérifié"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp_attempts",
            field=models.IntegerField(default=0, verbose_name="Tentatives OTP"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp_code",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Code OTP"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date création OTP"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True,
                error_messages={
                    "unique": "Ce numéro de téléphone est déjà associé à un compte."
                },
                max_length=20,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le numéro de téléphone doit être au format: +999999999",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Téléphone",
            ),
        ),
    ]
