# Generated by Django 5.0.7 on 2026-03-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_is_phone_verified_customuser_otp_attempts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=120, verbose_name="Nom complet")),
                (
                    "poste",
                    models.CharField(max_length=120, verbose_name="Poste / Rôle"),
                ),
                (
                    "departement",
                    models.CharField(
                        choices=[
                            ("direction", "Direction & Fondateurs"),
                            ("technique", "Équipe Technique & Développement"),
                            ("contenu", "Contenu & Communication"),
                            ("support", "Support & Service client"),
                            ("autre", "Autre"),
                        ],
                        default="technique",
                        max_length=30,
                        verbose_name="Département",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biographie courte")),
                (
                    "competences",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Django, PostgreSQL, PWA",
                        max_length=255,
                        verbose_name="Compétences (séparées par virgules)",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="staff/", verbose_name="Photo"
                    ),
                ),
                (
                    "initiales",
                    models.CharField(
                        blank=True,
                        help_text="Affiché si pas de photo. Ex: DG",
                        max_length=3,
                        verbose_name="Initiales (2-3 lettres)",
                    ),
                ),
                (
                    "ordre",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(
                        default=True, verbose_name="Affiché sur le site"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Membre du staff",
                "verbose_name_plural": "Membres du staff",
                "ordering": ["departement", "ordre", "nom"],
            },
        ),
    ]
