# Generated by Django 5.0.7 on 2026-03-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_staffmember_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Citation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.TextField(verbose_name="Texte de la citation")),
                (
                    "auteur",
                    models.CharField(
                        blank=True,
                        help_text="Ex : Victor Hugo, Proverbe africain…",
                        max_length=120,
                        verbose_name="Auteur / Source",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(
                        default=True,
                        help_text="Seules les citations actives sont affichées.",
                        verbose_name="Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Citation",
                "verbose_name_plural": "Citations",
                "ordering": ["id"],
            },
        ),
    ]
