#!/bin/bash

# 🎯 ESSENTIAL COMMANDS FOR BNC LIBRARY PROJECT
# Quick reference guide for developers

echo "════════════════════════════════════════════════════════════"
echo "📚 BNC LIBRARY - ESSENTIAL COMMANDS GUIDE"
echo "════════════════════════════════════════════════════════════"
echo ""

# Color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔧 SETUP & INITIALIZATION${NC}"
echo "─────────────────────────────────────────────────────────────"
echo "  python manage.py migrate              # Apply all migrations"
echo "  python manage.py check                # Verify Django setup"
echo "  python manage.py createsuperuser      # Create admin user"
echo "  python manage.py runserver            # Start dev server"
echo ""

echo -e "${BLUE}📊 DATABASE & MIGRATIONS${NC}"
echo "─────────────────────────────────────────────────────────────"
echo "  python manage.py makemigrations       # Create migrations"
echo "  python manage.py migrate              # Apply migrations"
echo "  python manage.py showmigrations       # View migration status"
echo "  python manage.py sqlmigrate <app> <migration>"
echo ""

echo -e "${BLUE}🧪 TESTING${NC}"
echo "─────────────────────────────────────────────────────────────"
echo "  bash test_integration.sh              # Run integration tests"
echo "  python manage.py test catalogue       # Run unit tests"
echo "  python manage.py shell                # Django interactive shell"
echo ""

echo -e "${BLUE}📁 ADMIN & MANAGEMENT${NC}"
echo "─────────────────────────────────────────────────────────────"
echo "  python manage.py createsuperuser      # Create admin account"
echo "  python manage.py shell < admin_setup.py  # Batch admin setup"
echo ""

echo -e "${BLUE}🔍 DEBUGGING${NC}"
echo "─────────────────────────────────────────────────────────────"
echo "  python manage.py check --deploy       # Check production readiness"
echo "  python manage.py check --verbosity 3  # Detailed checks"
echo "  python manage.py showmigrations --verbosity 3"
echo ""

echo -e "${BLUE}📝 CODE QUALITY${NC}"
echo "─────────────────────────────────────────────────────────────"
echo "  python manage.py check                # Django system check"
echo "  flake8 catalogue/                     # Lint checks"
echo "  black catalogue/                      # Format code"
echo ""

echo -e "${BLUE}🌐 API TESTING (via curl)${NC}"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "  # Payment Endpoints"
echo "  curl -X GET http://localhost:8000/api/payments/"
echo "  curl -X POST http://localhost:8000/api/payments/mobile-money/{book_id}/"
echo ""
echo "  # Free Preview Endpoints"
echo "  curl -X GET http://localhost:8000/api/book/{book_id}/can-read/"
echo "  curl -X GET http://localhost:8000/api/book/{book_id}/preview-pages/"
echo "  curl -X GET http://localhost:8000/api/book/{book_id}/page/10/access/"
echo ""
echo "  # Event Endpoints"
echo "  curl -X GET http://localhost:8000/api/events/"
echo "  curl -X GET http://localhost:8000/api/events/{event_id}/"
echo "  curl -X GET http://localhost:8000/api/events/upcoming/?limit=5"
echo ""
echo "  # Admin Panel"
echo "  curl -X GET http://localhost:8000/admin/"
echo ""

echo -e "${BLUE}🔐 ENVIRONMENT VARIABLES (Production)${NC}"
echo "─────────────────────────────────────────────────────────────"
echo "  AIRTEL_API_KEY=<your_airtel_key>"
echo "  AIRTEL_CLIENT_ID=<your_client_id>"
echo "  AIRTEL_CLIENT_SECRET=<your_secret>"
echo ""
echo "  MPESA_CONSUMER_KEY=<your_key>"
echo "  MPESA_CONSUMER_SECRET=<your_secret>"
echo ""
echo "  ORANGE_API_KEY=<your_key>"
echo "  ORANGE_SECRET=<your_secret>"
echo ""
echo "  DATABASE_URL=postgresql://user:pass@localhost/dbname"
echo "  SECRET_KEY=<long_random_key>"
echo "  DEBUG=False"
echo ""

echo -e "${BLUE}📚 DOCUMENTATION FILES${NC}"
echo "─────────────────────────────────────────────────────────────"
echo "  MOBILE_MONEY_PAYMENT_DOCUMENTATION.md"
echo "  FREE_PREVIEW_DOCUMENTATION.md"
echo "  DEVELOPER_ONBOARDING.md"
echo "  TECHNICAL_IMPLEMENTATION.md"
echo "  VERIFICATION_CHECKLIST.md"
echo ""

echo -e "${BLUE}🎯 COMMON WORKFLOWS${NC}"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "  Setup Project:"
echo "    python manage.py migrate"
echo "    python manage.py createsuperuser"
echo "    python manage.py runserver"
echo ""
echo "  Add New Payment Provider:"
echo "    # 1. Create gateway class in catalogue/payment_gateways.py"
echo "    # 2. Update get_payment_gateway() function"
echo "    # 3. Add webhook endpoint in catalogue/payment_views.py"
echo "    # 4. Add URL route in catalogue/urls.py"
echo "    python manage.py check"
echo ""
echo "  Create Event:"
echo "    python manage.py shell"
echo "    >>> from catalogue.models import Event"
echo "    >>> from django.utils import timezone"
echo "    >>> from datetime import timedelta"
echo "    >>> Event.objects.create("
echo "    ...     title='Tech Workshop',"
echo "    ...     event_type='WORKSHOP',"
echo "    ...     date_start=timezone.now() + timedelta(days=7)"
echo "    ... )"
echo ""
echo "  View Event Registrations:"
echo "    python manage.py shell"
echo "    >>> from catalogue.models import EventRegistration"
echo "    >>> EventRegistration.objects.select_related('user', 'event')"
echo ""

echo -e "${BLUE}📂 PROJECT STRUCTURE${NC}"
echo "─────────────────────────────────────────────────────────────"
echo "  /workspaces/bnc/"
echo "  ├── catalogue/               # Main app"
echo "  │   ├── models.py            # Event, EventRegistration"
echo "  │   ├── payment_gateways.py  # Payment providers"
echo "  │   ├── payment_views.py     # Payment endpoints"
echo "  │   ├── preview_views.py     # Free preview endpoints"
echo "  │   ├── events_views.py      # Events API"
echo "  │   ├── admin.py             # Admin interfaces"
echo "  │   ├── urls.py              # URL routing"
echo "  │   ├── migrations/          # Database migrations"
echo "  │   └── templates/           # HTML templates"
echo "  ├── config/                  # Django config"
echo "  ├── manage.py                # Django CLI"
echo "  ├── db.sqlite3               # Dev database"
echo "  └── Documentation files"
echo ""

echo -e "${BLUE}✨ USEFUL TIPS${NC}"
echo "─────────────────────────────────────────────────────────────"
echo "  # View all models"
echo "  python manage.py shell -c \"import django; print(django.apps.apps.get_models())\""
echo ""
echo "  # Count records in a table"
echo "  python manage.py shell -c \"from catalogue.models import Event; print(Event.objects.count())\""
echo ""
echo "  # Clear all data (be careful!)"
echo "  python manage.py flush"
echo ""
echo "  # View database schema"
echo "  python manage.py sqlmigrate catalogue 0016"
echo ""
echo "  # Create test data"
echo "  python manage.py shell < scripts/create_test_data.py"
echo ""

echo -e "${BLUE}🔗 IMPORTANT URLS${NC}"
echo "─────────────────────────────────────────────────────────────"
echo "  Django Admin:        http://localhost:8000/admin/"
echo "  Events:              http://localhost:8000/events/"
echo "  API Docs:            http://localhost:8000/api/"
echo "  Catalogue:           http://localhost:8000/"
echo ""

echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✓ Quick Reference Ready! Happy Coding! 🚀${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo ""
echo "For detailed docs, see:"
echo "  • DEVELOPER_ONBOARDING.md"
echo "  • TECHNICAL_IMPLEMENTATION.md"
echo "  • MOBILE_MONEY_PAYMENT_DOCUMENTATION.md"
echo ""
