services:
  - type: web
    name: bnc-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    disk:
      name: bnc-data
      mountPath: /var/data
      sizeGB: 10
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: bnc-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: RENDER_MEDIA_ROOT
        value: /var/data/media

databases:
  - name: bnc-db
    databaseName: bnc
    user: bnc_user
