#!/bin/bash
##############################################################################
# COMMANDES UTILES BNC - Helper script
# Usage: source scripts/commands.sh ou consulter ce fichier
##############################################################################

# 🚀 DÉMARRAGE & DÉVELOPPEMENT
echo "=== COMMANDES DÉVELOPPEMENT ==="
echo ""
echo "Démarrer le serveur:"
echo "  python manage.py runserver"
echo ""
echo "Créer un super-utilisateur:"
echo "  python manage.py createsuperuser"
echo ""
echo "Accès admin:"
echo "  http://localhost:8000/admin/"
echo ""
echo "Accès Jazzmin (admin moderne):"
echo "  http://localhost:8000/jazzmin/"
echo ""

# 🗄️ DATABASE
echo "=== COMMANDES DATABASE ==="
echo ""
echo "Créer migrations:"
echo "  python manage.py makemigrations"
echo ""
echo "Appliquer migrations:"
echo "  python manage.py migrate"
echo ""
echo "Afficher SQL migrations:"
echo "  python manage.py sqlmigrate catalogue 0001"
echo ""
echo "Shell Django (DB interactive):"
echo "  python manage.py shell"
echo "  >>> from catalogue.models import Book"
echo "  >>> Book.objects.count()"
echo ""

# 📦 TRADUCTIONS
echo "=== COMMANDES TRADUCTIONS ==="
echo ""
echo "Extraire les strings:"
echo "  ./scripts/manage_translations.sh extract"
echo ""
echo "Compiler les traductions:"
echo "  ./scripts/manage_translations.sh compile"
echo ""
echo "Mettre à jour (extract + compile):"
echo "  ./scripts/manage_translations.sh update"
echo ""
echo "Voir le statut:"
echo "  ./scripts/manage_translations.sh status"
echo ""
echo "Ajouter une langue (ex: espagnol):"
echo "  ./scripts/manage_translations.sh add es"
echo ""
echo "Générer un rapport:"
echo "  ./scripts/manage_translations.sh report"
echo ""

# 📚 LIVRES & DONNÉES
echo "=== IMPORTER DES LIVRES ==="
echo ""
echo "Importer depuis JSON:"
echo "  python manage.py loaddata fixtures/books.json"
echo ""
echo "Exporter données en JSON:"
echo "  python manage.py dumpdata catalogue > fixtures/books.json"
echo ""
echo "Créer des données de test:"
echo "  python manage.py shell"
echo "  >>> from catalogue.management.commands.create_test_data import Command"
echo "  >>> Command().handle()"
echo ""

# 🧪 TESTS
echo "=== TESTS & QUALITÉ ==="
echo ""
echo "Lancer tous les tests:"
echo "  python manage.py test"
echo ""
echo "Tests spécifiques:"
echo "  python manage.py test catalogue.tests.BookViewTestCase"
echo ""
echo "Avec verbosité:"
echo "  python manage.py test --verbosity=2"
echo ""
echo "Avec coverage:"
echo "  coverage run --source='.' manage.py test"
echo "  coverage report"
echo "  coverage html  # génère rapport HTML"
echo ""
echo "Linter (flake8):"
echo "  flake8 catalogue/ users/ --max-line-length=100"
echo ""
echo "Format code (black):"
echo "  black catalogue/ users/"
echo ""

# 🔐 SÉCURITÉ
echo "=== SÉCURITÉ ==="
echo ""
echo "Vérifier les issues de sécurité:"
echo "  python manage.py check --deploy"
echo ""
echo "Scan dépendances:"
echo "  safety check"
echo ""
echo "Changer la SECRET_KEY:"
echo "  python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
echo ""

# 📊 STATIC FILES
echo "=== STATIC FILES ==="
echo ""
echo "Collecter les static files:"
echo "  python manage.py collectstatic --noinput"
echo ""
echo "Mode développement (auto-collect):"
echo "  python manage.py runserver --insecure"
echo ""

# 🔧 MAINTENANCE
echo "=== MAINTENANCE ==="
echo ""
echo "Vider le cache:"
echo "  python manage.py clear_cache"
echo ""
echo "Nettoyer les sessions expirées:"
echo "  python manage.py clearsessions"
echo ""
echo "Vérifier la santé de l'app:"
echo "  python manage.py check"
echo ""
echo "Vider les migrations en cache:"
echo "  find . -type d -name __pycache__ -exec rm -rf {} +"
echo ""

# 🌐 DÉPLOIEMENT
echo "=== DÉPLOIEMENT ==="
echo ""
echo "Production setup:"
echo "  export DEBUG=False"
echo "  export SECRET_KEY=your-secret-key"
echo "  python manage.py migrate"
echo "  python manage.py collectstatic --noinput"
echo "  ./scripts/manage_translations.sh compile"
echo ""
echo "Avec Gunicorn:"
echo "  gunicorn config.wsgi:application --bind 0.0.0.0:8000"
echo ""
echo "Avec Docker:"
echo "  docker build -t bnc:latest ."
echo "  docker run -p 8000:8000 bnc:latest"
echo ""

# 📝 DONNÉES UTILES
echo "=== DONNÉES UTILES ==="
echo ""
echo "Compter les livres:"
echo "  python manage.py shell"
echo "  >>> from catalogue.models import Book"
echo "  >>> Book.objects.filter(is_published=True).count()"
echo ""
echo "Compter les utilisateurs:"
echo "  >>> from django.contrib.auth.models import User"
echo "  >>> User.objects.count()"
echo ""
echo "Livres les plus lus:"
echo "  >>> Book.objects.order_by('-reads_count')[:10]"
echo ""
echo "Utilisateurs actifs (derniers 7 jours):"
echo "  >>> from datetime import timedelta"
echo "  >>> from django.utils import timezone"
echo "  >>> week_ago = timezone.now() - timedelta(days=7)"
echo "  >>> User.objects.filter(last_login__gte=week_ago)"
echo ""

# 💡 ASTUCES
echo "=== ASTUCES ==="
echo ""
echo "Python interactive mode avec Django:"
echo "  python manage.py shell_plus  # ipython required"
echo ""
echo "Générer les messages en PDF:"
echo "  python manage.py makemessages -l fr"
echo ""
echo "Lister toutes les URLs:"
echo "  python manage.py show_urls"
echo ""
echo "Afficher les templates disponibles:"
echo "  python manage.py findtemplates"
echo ""
echo "Debugger avec pdb:"
echo "  python -m pdb manage.py runserver"
echo ""

# 🔗 URLS UTILES
echo "=== URLS IMPORTANTES ==="
echo ""
echo "Accueil:           http://localhost:8000/"
echo "Français:          http://localhost:8000/fr/"
echo "Admin:             http://localhost:8000/admin/"
echo "Jazzmin:           http://localhost:8000/jazzmin/"
echo "API docs:          http://localhost:8000/api/"
echo "Catalogue:         http://localhost:8000/fr/books/"
echo "Recommandations:   http://localhost:8000/api/books/recommendations/"
echo ""

echo "=========================================="
echo "Pour plus d'info: consulter README.md"
echo "=========================================="
