# Generated by Django 5.0.7 on 2026-03-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0032_donateur_contact_donateur_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudiobookProxy",
            fields=[],
            options={
                "verbose_name": "Audiobook",
                "verbose_name_plural": "Audiobooks",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalogue.audiobookmetadata",),
        ),
        migrations.CreateModel(
            name="PodcastProxy",
            fields=[],
            options={
                "verbose_name": "Podcast",
                "verbose_name_plural": "Podcasts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalogue.podcast",),
        ),
        migrations.CreateModel(
            name="VideoProxy",
            fields=[],
            options={
                "verbose_name": "Vidéo",
                "verbose_name_plural": "Vidéos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalogue.videomaterial",),
        ),
    ]
