# Generated by Django 5.0.7 on 2026-03-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0032_donateur_contact_donateur_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantAccountProxy",
            fields=[],
            options={
                "verbose_name": "Compte Marchand",
                "verbose_name_plural": "Comptes Marchands",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalogue.merchantpaymentaccount",),
        ),
        migrations.CreateModel(
            name="PaymentProxy",
            fields=[],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Historique des Paiements",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalogue.payment",),
        ),
    ]
