# Generated by Django 5.0.7 on 2026-03-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0032_donateur_contact_donateur_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventProxy",
            fields=[],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Agenda Événements",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalogue.event",),
        ),
    ]
