# Generated by Django 6.0 on 2025-12-04 09:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Nom"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Localisation"
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Pays")),
                ("city", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="libraries/%Y/%m/",
                        verbose_name="Logo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "max_users",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="Nombre maximum d'utilisateurs"
                    ),
                ),
                (
                    "current_users_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Utilisateurs actuels"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié"),
                ),
            ],
            options={
                "verbose_name": "Bibliothèque",
                "verbose_name_plural": "Bibliothèques",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LibraryBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Quantité totale"
                    ),
                ),
                (
                    "available_quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Quantité disponible"
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ajouté"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié"),
                ),
            ],
            options={
                "verbose_name": "Livre en bibliothèque",
                "verbose_name_plural": "Livres en bibliothèque",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XOF", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="ID de transaction"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("completed", "Complété"),
                            ("failed", "Échoué"),
                            ("refunded", "Remboursé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Carte de crédit"),
                            ("paypal", "PayPal"),
                            ("mobile_money", "Mobile Money"),
                            ("bank_transfer", "Virement bancaire"),
                            ("other", "Autre"),
                        ],
                        default="credit_card",
                        max_length=20,
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "receipt_url",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="receipts/%Y/%m/",
                        verbose_name="Reçu",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Payé"),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReadingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Début")),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fin"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Durée (minutes)"
                    ),
                ),
                (
                    "pages_read",
                    models.PositiveIntegerField(default=0, verbose_name="Pages lues"),
                ),
                (
                    "current_page",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Page actuelle"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Complété"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié"),
                ),
            ],
            options={
                "verbose_name": "Session de lecture",
                "verbose_name_plural": "Sessions de lecture",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("biography", models.TextField(blank=True, verbose_name="Biographie")),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="authors/%Y/%m/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        choices=[
                            ("SN", "Sénégal"),
                            ("ML", "Mali"),
                            ("CI", "Côte d'Ivoire"),
                            ("BJ", "Bénin"),
                            ("BF", "Burkina Faso"),
                            ("CM", "Cameroun"),
                            ("GH", "Ghana"),
                            ("KE", "Kenya"),
                            ("ZA", "Afrique du Sud"),
                            ("NG", "Nigéria"),
                            ("FR", "France"),
                            ("BE", "Belgique"),
                            ("CA", "Canada"),
                            ("US", "États-Unis"),
                            ("OTHER", "Autre"),
                        ],
                        default="OTHER",
                        max_length=50,
                        verbose_name="Nationalité",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                (
                    "verified_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de vérification"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié"),
                ),
            ],
            options={
                "verbose_name": "Auteur",
                "verbose_name_plural": "Auteurs",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="catalogue_a_last_na_524d59_idx",
                    ),
                    models.Index(fields=["email"], name="catalogue_a_email_4707e4_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuthorBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Auteur principal"),
                            ("contributor", "Contributeur"),
                            ("editor", "Éditeur"),
                            ("translator", "Traducteur"),
                        ],
                        default="primary",
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auteur du livre",
                "verbose_name_plural": "Auteurs du livre",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "isbn",
                    models.CharField(max_length=20, unique=True, verbose_name="ISBN"),
                ),
                (
                    "pages_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Nombre de pages"
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de publication"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "Anglais"),
                            ("ar", "Arabe"),
                            ("de", "Allemand"),
                            ("es", "Espagnol"),
                            ("pt", "Portugais"),
                            ("sw", "Swahili"),
                            ("other", "Autre"),
                        ],
                        default="fr",
                        max_length=10,
                        verbose_name="Langue",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("fiction", "Fiction"),
                            ("non_fiction", "Non-fiction"),
                            ("science", "Science"),
                            ("history", "Histoire"),
                            ("biography", "Biographie"),
                            ("children", "Enfants"),
                            ("poetry", "Poésie"),
                            ("drama", "Drame"),
                            ("mystery", "Mystère"),
                            ("romance", "Romance"),
                            ("fantasy", "Fantasy"),
                            ("self_help", "Développement personnel"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="books/covers/%Y/%m/",
                        verbose_name="Couverture",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="books/pdf/%Y/%m/",
                        verbose_name="Fichier PDF",
                    ),
                ),
                (
                    "epub_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="books/epub/%Y/%m/",
                        verbose_name="Fichier EPUB",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix",
                    ),
                ),
                (
                    "discount_percentage",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Pourcentage de réduction",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Payant")),
                (
                    "downloads_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de téléchargements"
                    ),
                ),
                (
                    "reads_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de lectures"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Note",
                    ),
                ),
                (
                    "rating_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d'évaluations"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Publié"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié"),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="books",
                        through="catalogue.AuthorBook",
                        to="catalogue.author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livre",
                "verbose_name_plural": "Livres",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="authorbook",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalogue.book"
            ),
        ),
    ]
