# Generated by Django 6.0 on 2025-12-04 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="libraries_admin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="librarybook",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalogue.book"
            ),
        ),
        migrations.AddField(
            model_name="librarybook",
            name="library",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalogue.library"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="libraries",
            field=models.ManyToManyField(
                related_name="books",
                through="catalogue.LibraryBook",
                to="catalogue.library",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="catalogue.book",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="readingsession",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reading_sessions",
                to="catalogue.book",
            ),
        ),
        migrations.AddField(
            model_name="readingsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reading_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="authorbook",
            unique_together={("author", "book", "role")},
        ),
        migrations.AddIndex(
            model_name="library",
            index=models.Index(fields=["name"], name="catalogue_l_name_cf6732_idx"),
        ),
        migrations.AddIndex(
            model_name="library",
            index=models.Index(
                fields=["is_active"], name="catalogue_l_is_acti_33bbf6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="librarybook",
            unique_together={("library", "book")},
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["isbn"], name="catalogue_b_isbn_fa8ee3_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["title"], name="catalogue_b_title_af9179_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["is_published"], name="catalogue_b_is_publ_8c153b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["genre"], name="catalogue_b_genre_2b3357_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "book"], name="catalogue_p_user_id_f6363e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="catalogue_p_status_d9b899_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["transaction_id"], name="catalogue_p_transac_137850_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="readingsession",
            index=models.Index(
                fields=["user", "book"], name="catalogue_r_user_id_d845a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="readingsession",
            index=models.Index(
                fields=["is_completed"], name="catalogue_r_is_comp_13bc0e_idx"
            ),
        ),
    ]
