# Generated by Django 6.0 on 2025-12-05 07:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("VIDEO", "Vidéo"),
                            ("PODCAST", "Podcast"),
                            ("INTERVIEW", "Interview"),
                            ("WEBINAR", "Webinaire"),
                        ],
                        max_length=50,
                        verbose_name="Type de média",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("YOUTUBE", "YouTube"),
                            ("SOUNDCLOUD", "SoundCloud"),
                            ("SPOTIFY", "Spotify"),
                            ("VIMEO", "Vimeo"),
                            ("CUSTOM", "Lien personnalisé"),
                        ],
                        max_length=50,
                        verbose_name="Plateforme",
                    ),
                ),
                ("url", models.URLField(verbose_name="URL externe")),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, verbose_name="URL de la miniature"),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Durée (minutes)"
                    ),
                ),
                (
                    "published_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de publication"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="catalogue.author",
                        verbose_name="Auteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Média d'auteur",
                "verbose_name_plural": "Médias d'auteur",
                "ordering": ["-published_date"],
                "indexes": [
                    models.Index(
                        fields=["author", "media_type"],
                        name="catalogue_a_author__884e52_idx",
                    ),
                    models.Index(
                        fields=["platform"], name="catalogue_a_platfor_83bdd1_idx"
                    ),
                ],
            },
        ),
    ]
