# Generated by Django 6.0 on 2025-12-15 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_authormedia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Nom"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nom d'icône FontAwesome (ex: fas fa-book)",
                        max_length=50,
                        verbose_name="Icône",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Code couleur hex (ex: #FF5733)",
                        max_length=7,
                        verbose_name="Couleur",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="catalogue.category",
                        verbose_name="Catégorie parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["parent", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BookCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Cocher si c'est la catégorie principale du livre",
                        verbose_name="Catégorie principale",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="catalogue.book",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="catalogue.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie du livre",
                "verbose_name_plural": "Catégories du livre",
            },
        ),
        migrations.CreateModel(
            name="ReaderActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("read", "Lecture"),
                            ("download", "Téléchargement"),
                            ("rate", "Évaluation"),
                            ("comment", "Commentaire"),
                            ("share", "Partage"),
                            ("bookmark", "Signet"),
                        ],
                        max_length=20,
                        verbose_name="Type d'activité",
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Détails"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Horodatage"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reader_activities",
                        to="catalogue.book",
                        verbose_name="Livre",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reader_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Lecteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activité de lecteur",
                "verbose_name_plural": "Activités de lecteur",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Création"),
                            ("update", "Modification"),
                            ("delete", "Suppression"),
                            ("login", "Connexion"),
                            ("logout", "Déconnexion"),
                            ("publish", "Publication"),
                            ("unpublish", "Dépublication"),
                            ("import", "Import"),
                            ("export", "Export"),
                            ("verify", "Vérification"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        help_text="Exemple: users.CustomUser, catalogue.Book",
                        max_length=100,
                        verbose_name="Type de contenu",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(max_length=255, verbose_name="ID de l'objet"),
                ),
                (
                    "object_str",
                    models.CharField(
                        help_text="Représentation textuelle de l'objet modifié",
                        max_length=500,
                        verbose_name="Représentation de l'objet",
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Détails supplémentaires au format JSON",
                        verbose_name="Détails",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Horodatage"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'audit",
                "verbose_name_plural": "Journaux d'audit",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="catalogue_a_user_id_e3ca3e_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="catalogue_a_action_89faee_idx",
                    ),
                    models.Index(
                        fields=["content_type"], name="catalogue_a_content_89f4b7_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="catalogue_a_timesta_995698_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="catalogue_c_slug_f8a9bd_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active"], name="catalogue_c_is_acti_e0ad75_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookcategory",
            unique_together={("book", "category")},
        ),
        migrations.AddIndex(
            model_name="readeractivity",
            index=models.Index(
                fields=["user", "timestamp"], name="catalogue_r_user_id_5608c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="readeractivity",
            index=models.Index(
                fields=["book", "timestamp"], name="catalogue_r_book_id_cfbf06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="readeractivity",
            index=models.Index(
                fields=["activity_type"], name="catalogue_r_activit_a15403_idx"
            ),
        ),
    ]
