# Generated by Django 6.0 on 2025-12-17 20:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0004_category_bookcategory_readeractivity_auditlog_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "page_number",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Numéro de page",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nom du signet"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#FF0000",
                        help_text="Code couleur hex",
                        max_length=7,
                        verbose_name="Couleur",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="catalogue.book",
                        verbose_name="Livre",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signet",
                "verbose_name_plural": "Signets",
                "ordering": ["page_number"],
                "indexes": [
                    models.Index(
                        fields=["user", "book"], name="catalogue_b_user_id_5cac91_idx"
                    )
                ],
                "unique_together": {("user", "book", "page_number")},
            },
        ),
        migrations.CreateModel(
            name="Highlight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "page_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Numéro de page"
                    ),
                ),
                (
                    "text",
                    models.TextField(max_length=1000, verbose_name="Texte surlignée"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#FFFF00",
                        help_text="Code couleur hex (défaut: jaune)",
                        max_length=7,
                        verbose_name="Couleur du surlignage",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Référence précise du passage",
                        max_length=255,
                        verbose_name="Localisation dans le livre",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, verbose_name="Note accompagnant le surlignage"
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=True,
                        help_text="Visible seulement par l'utilisateur si coché",
                        verbose_name="Privé",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="catalogue.book",
                        verbose_name="Livre",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Surlignage",
                "verbose_name_plural": "Surlignages",
                "ordering": ["page_number", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "book"], name="catalogue_h_user_id_ca30f7_idx"
                    ),
                    models.Index(
                        fields=["book", "is_private"],
                        name="catalogue_h_book_id_6c0f87_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="catalogue_h_created_857ea1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "page_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Numéro de page"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Titre"),
                ),
                ("content", models.TextField(verbose_name="Contenu de la note")),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Séparées par des virgules",
                        max_length=500,
                        verbose_name="Étiquettes",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="Épinglée"),
                ),
                (
                    "is_private",
                    models.BooleanField(default=True, verbose_name="Privée"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="catalogue.book",
                        verbose_name="Livre",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur de la note",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
                "ordering": ["-is_pinned", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "book"], name="catalogue_n_user_id_b54b6f_idx"
                    ),
                    models.Index(
                        fields=["is_pinned", "created_at"],
                        name="catalogue_n_is_pinn_5bda61_idx",
                    ),
                    models.Index(fields=["tags"], name="catalogue_n_tags_839025_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 étoile"),
                            (2, "2 étoiles"),
                            (3, "3 étoiles"),
                            (4, "4 étoiles"),
                            (5, "5 étoiles"),
                        ],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Note",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Titre de la critique"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="Contenu de la critique"),
                ),
                (
                    "is_spoiler",
                    models.BooleanField(
                        default=False, verbose_name="Contient des spoilers"
                    ),
                ),
                (
                    "helpful_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de lecteurs trouvant utile"
                    ),
                ),
                (
                    "unhelpful_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de lecteurs trouvant non-utile"
                    ),
                ),
                (
                    "is_verified_purchase",
                    models.BooleanField(default=False, verbose_name="Achat vérifiée"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalogue.book",
                        verbose_name="Livre",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Critique par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Critique",
                "verbose_name_plural": "Critiques",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["book", "is_published"],
                        name="catalogue_r_book_id_61ac1b_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="catalogue_r_user_id_6cfaa4_idx",
                    ),
                    models.Index(
                        fields=["rating"], name="catalogue_r_rating_1cc66d_idx"
                    ),
                ],
                "unique_together": {("user", "book")},
            },
        ),
    ]
