# Generated by Django 6.0 on 2025-12-18 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0006_favorite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="review",
            name="catalogue_r_book_id_61ac1b_idx",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="catalogue_r_user_id_6cfaa4_idx",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="catalogue_r_rating_1cc66d_idx",
        ),
        migrations.AddField(
            model_name="review",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="catalogue.book",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "1 - Très mauvais"),
                    (2, "2 - Mauvais"),
                    (3, "3 - Moyen"),
                    (4, "4 - Bon"),
                    (5, "5 - Excellent"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="review",
            name="content",
        ),
        migrations.RemoveField(
            model_name="review",
            name="helpful_count",
        ),
        migrations.RemoveField(
            model_name="review",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="review",
            name="is_spoiler",
        ),
        migrations.RemoveField(
            model_name="review",
            name="is_verified_purchase",
        ),
        migrations.RemoveField(
            model_name="review",
            name="title",
        ),
        migrations.RemoveField(
            model_name="review",
            name="unhelpful_count",
        ),
    ]
