# Generated by Django 6.0 on 2025-12-18 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0007_remove_review_catalogue_r_book_id_61ac1b_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bookmark",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="bookmark",
            name="catalogue_b_user_id_5cac91_idx",
        ),
        migrations.AlterModelOptions(
            name="highlight",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Surlignage",
                "verbose_name_plural": "Surlignages",
            },
        ),
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
            },
        ),
        migrations.RemoveIndex(
            model_name="highlight",
            name="catalogue_h_user_id_ca30f7_idx",
        ),
        migrations.RemoveIndex(
            model_name="highlight",
            name="catalogue_h_book_id_6c0f87_idx",
        ),
        migrations.RemoveIndex(
            model_name="highlight",
            name="catalogue_h_created_857ea1_idx",
        ),
        migrations.RemoveIndex(
            model_name="note",
            name="catalogue_n_user_id_b54b6f_idx",
        ),
        migrations.RemoveIndex(
            model_name="note",
            name="catalogue_n_is_pinn_5bda61_idx",
        ),
        migrations.RemoveIndex(
            model_name="note",
            name="catalogue_n_tags_839025_idx",
        ),
        migrations.AddField(
            model_name="note",
            name="highlight",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note",
                to="catalogue.highlight",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="highlight",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlights",
                to="catalogue.book",
            ),
        ),
        migrations.AlterField(
            model_name="highlight",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="highlight",
            name="page_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="highlight",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="highlight",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlights",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="catalogue.book",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="highlight",
            name="color",
        ),
        migrations.RemoveField(
            model_name="highlight",
            name="is_private",
        ),
        migrations.RemoveField(
            model_name="highlight",
            name="location",
        ),
        migrations.RemoveField(
            model_name="highlight",
            name="note",
        ),
        migrations.RemoveField(
            model_name="highlight",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="note",
            name="content",
        ),
        migrations.RemoveField(
            model_name="note",
            name="is_pinned",
        ),
        migrations.RemoveField(
            model_name="note",
            name="is_private",
        ),
        migrations.RemoveField(
            model_name="note",
            name="page_number",
        ),
        migrations.RemoveField(
            model_name="note",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="note",
            name="title",
        ),
        migrations.DeleteModel(
            name="Bookmark",
        ),
    ]
