# Generated by Django 6.0 on 2025-12-18 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0008_alter_bookmark_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("NEW_BOOK", "Nouveau livre"),
                            ("WORKSHOP", "Atelier"),
                            ("CONFERENCE", "Conférence"),
                            ("ANNOUNCEMENT", "Annonce"),
                            ("LOCAL_EVENT", "Événement local"),
                        ],
                        default="ANNOUNCEMENT",
                        max_length=20,
                        verbose_name="Type d'événement",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/%Y/%m/",
                        verbose_name="Image",
                    ),
                ),
                ("date_start", models.DateTimeField(verbose_name="Date de début")),
                (
                    "date_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Lieu"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Lien externe pour plus d'infos",
                        null=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="catalogue.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "ordering": ["-date_start"],
                "indexes": [
                    models.Index(
                        fields=["event_type"], name="catalogue_e_event_t_25a1ff_idx"
                    ),
                    models.Index(
                        fields=["is_published", "-date_start"],
                        name="catalogue_e_is_publ_19db64_idx",
                    ),
                ],
            },
        ),
    ]
