# Generated by Django 6.0 on 2025-12-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0009_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="free_pages_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Nombre de pages accessibles gratuitement (0 = aucune preview)",
                verbose_name="Nombre de pages libres",
            ),
        ),
    ]
