# Generated by Django 6.0 on 2025-12-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0010_book_free_pages_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="external_transaction_id",
            field=models.CharField(
                blank=True,
                help_text="ID de transaction du fournisseur de paiement (Stripe, PayPal, etc.)",
                max_length=255,
                verbose_name="ID de transaction externe",
            ),
        ),
    ]
