# Generated by Django 6.0 on 2025-12-19 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0011_payment_external_transaction_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="readingsession",
            name="progress_percent",
            field=models.IntegerField(default=0, verbose_name="Progression (%)"),
        ),
        migrations.AddIndex(
            model_name="readingsession",
            index=models.Index(
                fields=["progress_percent"], name="catalogue_r_progres_a774ba_idx"
            ),
        ),
    ]
