# Generated by Django 6.0 on 2025-12-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0012_readingsession_progress_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="highlight",
            name="color",
            field=models.CharField(default="#FFEB3B", max_length=7),
        ),
        migrations.AddField(
            model_name="highlight",
            name="coordinates",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
