# Generated by Django 6.0 on 2025-12-19 21:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0013_highlight_color_highlight_coordinates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "french_preference",
                    models.FloatField(
                        default=0.5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Préférence Français",
                    ),
                ),
                (
                    "english_preference",
                    models.FloatField(
                        default=0.5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Préférence Anglais",
                    ),
                ),
                (
                    "arabic_preference",
                    models.FloatField(
                        default=0.5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Préférence Arabe",
                    ),
                ),
                (
                    "total_ratings",
                    models.IntegerField(default=0, verbose_name="Total évaluations"),
                ),
                (
                    "avg_rating",
                    models.FloatField(default=0.0, verbose_name="Note moyenne"),
                ),
                (
                    "books_read",
                    models.IntegerField(default=0, verbose_name="Livres lus"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date créée"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date mise à jour"
                    ),
                ),
                (
                    "preferred_authors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="preference_users",
                        to="catalogue.author",
                    ),
                ),
                (
                    "preferred_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="preference_users",
                        to="catalogue.category",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence utilisateur",
                "verbose_name_plural": "Préférences utilisateur",
            },
        ),
        migrations.CreateModel(
            name="BookRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "⭐ Mauvais"),
                            (2, "⭐⭐ Faible"),
                            (3, "⭐⭐⭐ Moyen"),
                            (4, "⭐⭐⭐⭐ Bon"),
                            (5, "⭐⭐⭐⭐⭐ Excellent"),
                        ],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Évaluation",
                    ),
                ),
                (
                    "review",
                    models.TextField(blank=True, null=True, verbose_name="Avis"),
                ),
                ("is_helpful", models.BooleanField(default=True, verbose_name="Utile")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date créée"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date mise à jour"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_ratings",
                        to="catalogue.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation de livre",
                "verbose_name_plural": "Évaluations de livres",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "rating"], name="catalogue_b_user_id_7be8de_idx"
                    ),
                    models.Index(
                        fields=["book", "rating"], name="catalogue_b_book_id_1de569_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="catalogue_b_created_aa0c7b_idx"
                    ),
                ],
                "unique_together": {("user", "book")},
            },
        ),
        migrations.CreateModel(
            name="BookSimilarity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category_similarity",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Similarité catégorie",
                    ),
                ),
                (
                    "author_similarity",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Similarité auteur",
                    ),
                ),
                (
                    "tag_similarity",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Similarité tags",
                    ),
                ),
                (
                    "overall_similarity",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Similarité globale",
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Calculé le"),
                ),
                (
                    "book1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities_as_book1",
                        to="catalogue.book",
                    ),
                ),
                (
                    "book2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities_as_book2",
                        to="catalogue.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Similarité de livres",
                "verbose_name_plural": "Similarités de livres",
                "ordering": ["-overall_similarity"],
                "indexes": [
                    models.Index(
                        fields=["book1", "-overall_similarity"],
                        name="catalogue_b_book1_i_ca1e3d_idx",
                    ),
                    models.Index(
                        fields=["book2", "-overall_similarity"],
                        name="catalogue_b_book2_i_ddc310_idx",
                    ),
                ],
                "unique_together": {("book1", "book2")},
            },
        ),
        migrations.CreateModel(
            name="TrendingBook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("1d", "24 heures"),
                            ("7d", "7 jours"),
                            ("30d", "30 jours"),
                            ("90d", "90 jours"),
                        ],
                        max_length=3,
                        verbose_name="Période",
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Classement",
                    ),
                ),
                (
                    "reads_count",
                    models.IntegerField(default=0, verbose_name="Nombre de lectures"),
                ),
                (
                    "ratings_count",
                    models.IntegerField(default=0, verbose_name="Nombre d'évaluations"),
                ),
                (
                    "avg_rating",
                    models.FloatField(default=0.0, verbose_name="Note moyenne"),
                ),
                (
                    "purchases_count",
                    models.IntegerField(default=0, verbose_name="Nombre d'achats"),
                ),
                (
                    "trend_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Score de tendance",
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Calculé le"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trending_entries",
                        to="catalogue.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livre en tendance",
                "verbose_name_plural": "Livres en tendance",
                "ordering": ["period", "rank"],
                "indexes": [
                    models.Index(
                        fields=["period", "rank"], name="catalogue_t_period_329e4e_idx"
                    ),
                    models.Index(
                        fields=["period", "-trend_score"],
                        name="catalogue_t_period_e65ace_idx",
                    ),
                    models.Index(
                        fields=["-calculated_at"], name="catalogue_t_calcula_32f698_idx"
                    ),
                ],
                "unique_together": {("book", "period")},
            },
        ),
        migrations.CreateModel(
            name="UserRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("collaborative", "Collaborative Filtering"),
                            ("content_based", "Content-Based"),
                            ("hybrid", "Hybride"),
                            ("trending", "En Tendance"),
                            ("similar", "Livres Similaires"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        help_text="Score de pertinence 0-100",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Score",
                    ),
                ),
                (
                    "is_viewed",
                    models.BooleanField(default=False, verbose_name="Consulté"),
                ),
                ("is_liked", models.BooleanField(default=False, verbose_name="Aimé")),
                (
                    "is_purchased",
                    models.BooleanField(default=False, verbose_name="Acheté"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date créée"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expire le"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="catalogue.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommandation utilisateur",
                "verbose_name_plural": "Recommandations utilisateur",
                "ordering": ["-score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-score"], name="catalogue_u_user_id_5e4a03_idx"
                    ),
                    models.Index(
                        fields=["user", "is_viewed"],
                        name="catalogue_u_user_id_2d2f6f_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="catalogue_u_created_0ef28f_idx"
                    ),
                ],
                "unique_together": {("user", "book", "recommendation_type")},
            },
        ),
    ]
