# Generated by Django 6.0 on 2025-12-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0014_userpreference_bookrating_booksimilarity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="checkout_request_id",
            field=models.CharField(
                blank=True,
                help_text="ID fourni par le provider pour polling du statut",
                max_length=255,
                null=True,
                verbose_name="ID requête checkout",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="merchant_request_id",
            field=models.CharField(
                blank=True,
                help_text="ID interne pour suivi",
                max_length=255,
                null=True,
                verbose_name="ID requête marchand",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="mobile_money_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("airtel", "Airtel Money"),
                    ("mpesa", "M-Pesa"),
                    ("orange", "Orange Money"),
                ],
                help_text="Airtel, M-Pesa, ou Orange Money",
                max_length=20,
                null=True,
                verbose_name="Fournisseur Mobile Money",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Format: +256xxxxxxxxx (Airtel), +254xxxxxxxxx (M-Pesa), +243xxxxxxxxx (Orange RDC)",
                max_length=20,
                null=True,
                verbose_name="Numéro de téléphone",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="webhook_data",
            field=models.JSONField(
                blank=True,
                help_text="Réponse brute du webhook du provider",
                null=True,
                verbose_name="Données webhook",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Carte de crédit"),
                    ("paypal", "PayPal"),
                    ("airtel_money", "Airtel Money"),
                    ("mpesa", "M-Pesa"),
                    ("orange_money", "Orange Money RDC"),
                    ("bank_transfer", "Virement bancaire"),
                    ("other", "Autre"),
                ],
                default="credit_card",
                max_length=20,
                verbose_name="Méthode de paiement",
            ),
        ),
    ]
