# Generated by Django 6.0 on 2025-12-21 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0015_payment_checkout_request_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'inscription"
                    ),
                ),
                (
                    "attended",
                    models.BooleanField(default=False, verbose_name="Présent"),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="Retours"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="catalogue.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription événement",
                "verbose_name_plural": "Inscriptions événements",
                "ordering": ["-registered_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-registered_at"],
                        name="catalogue_e_user_id_76d072_idx",
                    ),
                    models.Index(
                        fields=["event", "-registered_at"],
                        name="catalogue_e_event_i_672d0c_idx",
                    ),
                    models.Index(
                        fields=["attended"], name="catalogue_e_attende_cd1f6b_idx"
                    ),
                ],
                "unique_together": {("user", "event")},
            },
        ),
    ]
