# Generated by Django 6.0 on 2025-12-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0016_eventregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantPaymentAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Carte de crédit"),
                            ("paypal", "PayPal"),
                            ("airtel_money", "Airtel Money"),
                            ("mpesa", "M-Pesa"),
                            ("orange_money", "Orange Money RDC"),
                            ("bank_transfer", "Virement bancaire"),
                            ("other", "Autre"),
                        ],
                        help_text="Chaque méthode ne peut avoir qu'un seul compte",
                        max_length=20,
                        unique=True,
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="Numéro Orange Money, M-Pesa, IBAN, etc.",
                        max_length=255,
                        verbose_name="Numéro de compte/téléphone",
                    ),
                ),
                (
                    "account_holder_name",
                    models.CharField(
                        blank=True,
                        help_text="Nom sous lequel le compte est enregistré",
                        max_length=255,
                        verbose_name="Nom du titulaire",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Banque du Congo, Orange, Airtel, etc.",
                        max_length=255,
                        verbose_name="Nom de la banque/Provider",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Désactiver si ce compte ne reçoit plus de paiements",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Instructions spéciales ou remarques (non visible aux clients)",
                        verbose_name="Notes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Compte de perception",
                "verbose_name_plural": "Comptes de perception",
                "ordering": ["payment_method"],
            },
        ),
    ]
