# Generated by Django 6.0 on 2025-12-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0017_merchantpaymentaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="country_origin",
            field=models.CharField(
                blank=True,
                help_text="Pays de publication ou d'origine du livre",
                max_length=100,
                verbose_name="Pays d'origine",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.CharField(
                blank=True,
                help_text="Nom de l'éditeur ou de la maison d'édition",
                max_length=255,
                verbose_name="Éditeur",
            ),
        ),
    ]
