# Generated by Django 6.0 on 2025-12-23 19:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0018_add_publisher_and_country_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAchievements",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        choices=[
                            ("first_book", "Premier Livre"),
                            ("collector_5", "Collectionneur (5 livres)"),
                            ("collector_10", "Collectionneur Pro (10 livres)"),
                            ("collector_25", "Maître Collectionneur (25 livres)"),
                            ("speed_reader_10h", "Lecteur Rapide (10h)"),
                            ("speed_reader_50h", "Super Lecteur (50h)"),
                            ("speed_reader_100h", "Lecteur Légendaire (100h)"),
                            ("genre_master_fiction", "Maître Fiction"),
                            ("genre_master_science", "Maître Science"),
                            ("reviewer", "Critique"),
                            ("note_taker", "Preneur de Notes"),
                            ("social_butterfly", "Papillon Social"),
                        ],
                        max_length=50,
                        verbose_name="Badge",
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Obtenu le"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accomplissement",
                "verbose_name_plural": "Accomplissements",
                "indexes": [
                    models.Index(
                        fields=["user"], name="catalogue_u_user_id_2dc58b_idx"
                    ),
                    models.Index(fields=["badge"], name="catalogue_u_badge_9435ee_idx"),
                ],
                "unique_together": {("user", "badge")},
            },
        ),
        migrations.CreateModel(
            name="UserAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_books_read",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total livres lus",
                    ),
                ),
                (
                    "total_books_in_progress",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Livres en cours",
                    ),
                ),
                (
                    "total_pages_read",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total pages lues",
                    ),
                ),
                (
                    "total_reading_hours",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Heures de lecture totales",
                    ),
                ),
                (
                    "average_reading_pace",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Rythme de lecture moyen (pages/heure)",
                    ),
                ),
                (
                    "total_reviews",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total avis écrits",
                    ),
                ),
                (
                    "average_book_rating",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Note moyenne donnée",
                    ),
                ),
                (
                    "total_notes",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total notes prises",
                    ),
                ),
                (
                    "total_highlights",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total highlights",
                    ),
                ),
                (
                    "favorite_genre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Genre préféré",
                    ),
                ),
                (
                    "favorite_author",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Auteur préféré",
                    ),
                ),
                (
                    "favorite_language",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Langue préférée",
                    ),
                ),
                (
                    "reading_streak_days",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Jours de lecture consécutifs",
                    ),
                ),
                (
                    "last_reading_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière lecture"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Utilisateur",
                "verbose_name_plural": "Analytics Utilisateurs",
                "indexes": [
                    models.Index(
                        fields=["user"], name="catalogue_u_user_id_df1304_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="catalogue_u_updated_a333dd_idx"
                    ),
                ],
            },
        ),
    ]
