# Generated by Django 6.0 on 2025-12-24 09:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0020_forum_phase8_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AudiobookChapter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chapter_number",
                    models.IntegerField(verbose_name="Numéro du chapitre"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "duration_seconds",
                    models.IntegerField(verbose_name="Durée (secondes)"),
                ),
                (
                    "start_time",
                    models.IntegerField(verbose_name="Temps de départ (secondes)"),
                ),
                (
                    "end_time",
                    models.IntegerField(verbose_name="Temps de fin (secondes)"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Disponible"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
            ],
            options={
                "verbose_name": "Chapitre Audiobook",
                "verbose_name_plural": "Chapitres Audiobook",
                "ordering": ["chapter_number"],
            },
        ),
        migrations.CreateModel(
            name="AudiobookMetadata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "narrator",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Narrateur"
                    ),
                ),
                (
                    "duration_hours",
                    models.FloatField(default=0.0, verbose_name="Durée (heures)"),
                ),
                (
                    "bitrate",
                    models.CharField(
                        default="128 kbps", max_length=50, verbose_name="Débit binaire"
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        default="mp3", max_length=20, verbose_name="Format"
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="audiobooks/%Y/%m/",
                        verbose_name="Fichier audio",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="audiobook_covers/%Y/%m/",
                        verbose_name="Image de couverture",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Publié"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Audiobook",
                "verbose_name_plural": "Audiobooks",
            },
        ),
        migrations.CreateModel(
            name="ListeningProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_chapter",
                    models.IntegerField(default=0, verbose_name="Chapitre actuel"),
                ),
                (
                    "current_time",
                    models.IntegerField(
                        default=0, verbose_name="Temps actuel (secondes)"
                    ),
                ),
                (
                    "total_time_listened",
                    models.IntegerField(
                        default=0, verbose_name="Temps écouté total (secondes)"
                    ),
                ),
                (
                    "completion_percentage",
                    models.FloatField(default=0.0, verbose_name="Pourcentage complété"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Complété"),
                ),
                (
                    "last_listened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière écoute"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Progression Écoute",
                "verbose_name_plural": "Progressions Écoute",
            },
        ),
        migrations.CreateModel(
            name="PDFAnnotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "annotation_type",
                    models.CharField(
                        choices=[
                            ("highlight", "Surlignage"),
                            ("note", "Note"),
                            ("bookmark", "Marque-page"),
                            ("underline", "Souligné"),
                            ("strikethrough", "Barré"),
                        ],
                        default="highlight",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("page_number", models.IntegerField(verbose_name="Numéro de page")),
                (
                    "x_start",
                    models.FloatField(default=0.0, verbose_name="Position X départ"),
                ),
                (
                    "y_start",
                    models.FloatField(default=0.0, verbose_name="Position Y départ"),
                ),
                (
                    "x_end",
                    models.FloatField(default=0.0, verbose_name="Position X fin"),
                ),
                (
                    "y_end",
                    models.FloatField(default=0.0, verbose_name="Position Y fin"),
                ),
                ("text", models.TextField(blank=True, verbose_name="Texte annoté")),
                (
                    "color",
                    models.CharField(
                        default="#FFFF00", max_length=7, verbose_name="Couleur"
                    ),
                ),
                (
                    "note_content",
                    models.TextField(blank=True, verbose_name="Contenu de la note"),
                ),
                (
                    "is_synced",
                    models.BooleanField(default=False, verbose_name="Synchronisé"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Annotation PDF",
                "verbose_name_plural": "Annotations PDF",
                "ordering": ["page_number", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Créateur"
                    ),
                ),
                (
                    "rss_feed_url",
                    models.URLField(blank=True, verbose_name="URL du flux RSS"),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, verbose_name="URL de l'image"),
                ),
                ("website_url", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "language",
                    models.CharField(
                        default="fr", max_length=10, verbose_name="Langue"
                    ),
                ),
                (
                    "episode_count",
                    models.IntegerField(default=0, verbose_name="Nombre d'épisodes"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière synchronisation"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Podcast",
                "verbose_name_plural": "Podcasts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PodcastEpisode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "episode_number",
                    models.IntegerField(verbose_name="Numéro d'épisode"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(default=0, verbose_name="Durée (secondes)"),
                ),
                ("audio_url", models.URLField(verbose_name="URL audio")),
                (
                    "pubdate",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de publication"
                    ),
                ),
                (
                    "guid",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="GUID",
                    ),
                ),
                (
                    "is_explicit",
                    models.BooleanField(
                        default=False, verbose_name="Contenu explicite"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
            ],
            options={
                "verbose_name": "Épisode Podcast",
                "verbose_name_plural": "Épisodes Podcast",
                "ordering": ["-episode_number"],
            },
        ),
        migrations.CreateModel(
            name="PodcastProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_time",
                    models.IntegerField(
                        default=0, verbose_name="Temps actuel (secondes)"
                    ),
                ),
                (
                    "completion_percentage",
                    models.FloatField(default=0.0, verbose_name="Pourcentage complété"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Complété"),
                ),
                (
                    "playback_count",
                    models.IntegerField(default=0, verbose_name="Nombre de lectures"),
                ),
                (
                    "is_bookmarked",
                    models.BooleanField(default=False, verbose_name="Marqué"),
                ),
                (
                    "last_played_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière lecture"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Progression Podcast",
                "verbose_name_plural": "Progressions Podcast",
            },
        ),
        migrations.CreateModel(
            name="PodcastSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "notification_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Notifications activées"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Abonnement Podcast",
                "verbose_name_plural": "Abonnements Podcast",
            },
        ),
        migrations.CreateModel(
            name="VideoMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "video_type",
                    models.CharField(
                        choices=[
                            ("adaptation", "Adaptation filmique"),
                            ("review", "Critique"),
                            ("interview", "Entrevue"),
                            ("reading", "Lecture"),
                            ("tutorial", "Tutoriel"),
                            ("other", "Autre"),
                        ],
                        default="adaptation",
                        max_length=20,
                        verbose_name="Type de vidéo",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="videos/%Y/%m/",
                        verbose_name="Fichier vidéo",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, verbose_name="URL externe"),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(default=0, verbose_name="Durée (secondes)"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="video_thumbnails/%Y/%m/",
                        verbose_name="Miniature",
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(default=0, verbose_name="Nombre de vues"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Publié"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Matériau Vidéo",
                "verbose_name_plural": "Matériaux Vidéo",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoPlayback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_time",
                    models.IntegerField(
                        default=0, verbose_name="Temps actuel (secondes)"
                    ),
                ),
                (
                    "completion_percentage",
                    models.FloatField(default=0.0, verbose_name="Pourcentage complété"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Complété"),
                ),
                (
                    "playback_count",
                    models.IntegerField(default=0, verbose_name="Nombre de lectures"),
                ),
                (
                    "last_played_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière lecture"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Lecture Vidéo",
                "verbose_name_plural": "Lectures Vidéo",
            },
        ),
        migrations.AlterUniqueTogether(
            name="userachievements",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="userachievements",
            name="catalogue_u_user_id_2dc58b_idx",
        ),
        migrations.RemoveIndex(
            model_name="userachievements",
            name="catalogue_u_badge_9435ee_idx",
        ),
        migrations.RemoveIndex(
            model_name="useranalytics",
            name="catalogue_u_user_id_df1304_idx",
        ),
        migrations.RemoveIndex(
            model_name="useranalytics",
            name="catalogue_u_updated_a333dd_idx",
        ),
        migrations.RemoveField(
            model_name="book",
            name="country_origin",
        ),
        migrations.RemoveField(
            model_name="book",
            name="publisher",
        ),
        migrations.AddField(
            model_name="audiobookmetadata",
            name="book",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audiobook",
                to="catalogue.book",
                verbose_name="Livre",
            ),
        ),
        migrations.AddField(
            model_name="audiobookchapter",
            name="audiobook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="catalogue.audiobookmetadata",
                verbose_name="Audiobook",
            ),
        ),
        migrations.AddField(
            model_name="listeningprogress",
            name="audiobook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listening_sessions",
                to="catalogue.audiobookmetadata",
                verbose_name="Audiobook",
            ),
        ),
        migrations.AddField(
            model_name="listeningprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listening_progress",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="pdfannotation",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pdf_annotations",
                to="catalogue.book",
                verbose_name="Livre",
            ),
        ),
        migrations.AddField(
            model_name="pdfannotation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pdf_annotations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="podcast",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="podcasts",
                to="catalogue.book",
                verbose_name="Livre",
            ),
        ),
        migrations.AddField(
            model_name="podcastepisode",
            name="podcast",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episodes",
                to="catalogue.podcast",
                verbose_name="Podcast",
            ),
        ),
        migrations.AddField(
            model_name="podcastprogress",
            name="episode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_progress",
                to="catalogue.podcastepisode",
                verbose_name="Épisode",
            ),
        ),
        migrations.AddField(
            model_name="podcastprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="podcast_progress",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="podcastsubscription",
            name="podcast",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="catalogue.podcast",
                verbose_name="Podcast",
            ),
        ),
        migrations.AddField(
            model_name="podcastsubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="podcast_subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="videomaterial",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_materials",
                to="catalogue.book",
                verbose_name="Livre",
            ),
        ),
        migrations.AddField(
            model_name="videomaterial",
            name="uploader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_videos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Téléchargé par",
            ),
        ),
        migrations.AddField(
            model_name="videoplayback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_playbacks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="videoplayback",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playback_history",
                to="catalogue.videomaterial",
                verbose_name="Vidéo",
            ),
        ),
        migrations.RemoveField(
            model_name="userachievements",
            name="user",
        ),
        migrations.RemoveField(
            model_name="useranalytics",
            name="user",
        ),
        migrations.AddIndex(
            model_name="audiobookchapter",
            index=models.Index(
                fields=["audiobook", "chapter_number"],
                name="catalogue_a_audiobo_159bb8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="listeningprogress",
            index=models.Index(
                fields=["user", "audiobook"], name="catalogue_l_user_id_04a2cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listeningprogress",
            index=models.Index(
                fields=["is_completed"], name="catalogue_l_is_comp_bd69e2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="listeningprogress",
            unique_together={("user", "audiobook")},
        ),
        migrations.AddIndex(
            model_name="pdfannotation",
            index=models.Index(
                fields=["user", "book"], name="catalogue_p_user_id_fb9e8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pdfannotation",
            index=models.Index(
                fields=["book", "page_number"], name="catalogue_p_book_id_98ee70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pdfannotation",
            index=models.Index(
                fields=["is_synced"], name="catalogue_p_is_sync_909a37_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pdfannotation",
            unique_together={("user", "book", "page_number", "x_start", "y_start")},
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(
                fields=["is_active"], name="catalogue_p_is_acti_f475cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="podcast",
            index=models.Index(fields=["book"], name="catalogue_p_book_id_94c59b_idx"),
        ),
        migrations.AddIndex(
            model_name="podcastepisode",
            index=models.Index(
                fields=["podcast", "episode_number"],
                name="catalogue_p_podcast_6dafa2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="podcastepisode",
            index=models.Index(fields=["guid"], name="catalogue_p_guid_2769ac_idx"),
        ),
        migrations.AddIndex(
            model_name="podcastprogress",
            index=models.Index(
                fields=["user", "episode"], name="catalogue_p_user_id_d4497c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="podcastprogress",
            index=models.Index(
                fields=["is_completed"], name="catalogue_p_is_comp_25e8ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="podcastprogress",
            index=models.Index(
                fields=["is_bookmarked"], name="catalogue_p_is_book_4d5437_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="podcastprogress",
            unique_together={("user", "episode")},
        ),
        migrations.AddIndex(
            model_name="podcastsubscription",
            index=models.Index(
                fields=["user", "is_active"], name="catalogue_p_user_id_8eebae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="podcastsubscription",
            index=models.Index(
                fields=["podcast"], name="catalogue_p_podcast_97f13c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="podcastsubscription",
            unique_together={("user", "podcast")},
        ),
        migrations.AddIndex(
            model_name="videomaterial",
            index=models.Index(
                fields=["book", "video_type"], name="catalogue_v_book_id_dc390d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videomaterial",
            index=models.Index(
                fields=["is_published"], name="catalogue_v_is_publ_06847e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videoplayback",
            index=models.Index(
                fields=["user", "video"], name="catalogue_v_user_id_1f3f3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videoplayback",
            index=models.Index(
                fields=["is_completed"], name="catalogue_v_is_comp_27825c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="videoplayback",
            unique_together={("user", "video")},
        ),
        migrations.DeleteModel(
            name="UserAchievements",
        ),
        migrations.DeleteModel(
            name="UserAnalytics",
        ),
    ]
