# Generated by Django 6.0 on 2025-12-26 12:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogue",
            "0021_audiobookchapter_audiobookmetadata_listeningprogress_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationStatistic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="Nombre de vues"),
                ),
                (
                    "clicked_count",
                    models.IntegerField(default=0, verbose_name="Nombre de clics"),
                ),
                (
                    "purchased_count",
                    models.IntegerField(default=0, verbose_name="Nombre d'achats"),
                ),
                (
                    "read_count",
                    models.IntegerField(default=0, verbose_name="Nombre de lectures"),
                ),
                (
                    "feedback_rating",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Note de feedback",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date créée"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date mise à jour"
                    ),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistic",
                        to="catalogue.userrecommendation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistique de recommandation",
                "verbose_name_plural": "Statistiques de recommandation",
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="catalogue_r_created_78d999_idx"
                    ),
                    models.Index(
                        fields=["recommendation"], name="catalogue_r_recomme_d1dc6a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("bookmark_add", "Ajouter un signet"),
                            ("bookmark_remove", "Supprimer un signet"),
                            ("note_add", "Ajouter une note"),
                            ("note_update", "Mettre à jour une note"),
                            ("note_delete", "Supprimer une note"),
                            ("highlight_add", "Ajouter un surlignage"),
                            ("highlight_delete", "Supprimer un surlignage"),
                            ("rating_add", "Ajouter une note/évaluation"),
                            (
                                "reading_position_update",
                                "Mise à jour position de lecture",
                            ),
                        ],
                        max_length=30,
                        verbose_name="Action",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="Données sérialisées JSON", verbose_name="Données"
                    ),
                ),
                (
                    "synced",
                    models.BooleanField(default=False, verbose_name="Synchronisé"),
                ),
                (
                    "sync_attempts",
                    models.IntegerField(default=0, verbose_name="Tentatives de sync"),
                ),
                (
                    "last_sync_attempt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernier essai de sync"
                    ),
                ),
                (
                    "sync_error",
                    models.TextField(blank=True, verbose_name="Erreur de sync"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date créée"),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date synchronisée"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_queue",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Queue de synchronisation",
                "verbose_name_plural": "Queues de synchronisation",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "synced"], name="catalogue_s_user_id_7b4a71_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="catalogue_s_created_409ba7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserRecommendationFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feedback",
                    models.CharField(
                        choices=[
                            ("like", "J'aime"),
                            ("dislike", "Je n'aime pas"),
                            ("useful", "Utile"),
                            ("not_useful", "Pas utile"),
                            ("already_read", "Déjà lu"),
                            ("not_interested", "Pas intéressé"),
                        ],
                        max_length=20,
                        verbose_name="Type de feedback",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Commentaire")),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Note (1-5)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date créée"),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="catalogue.userrecommendation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback de recommandation",
                "verbose_name_plural": "Feedbacks de recommandation",
                "ordering": ["-created_at"],
                "unique_together": {("user", "recommendation")},
            },
        ),
    ]
