# Generated by Django 6.0 on 2026-01-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0022_recommendationstatistic_syncqueue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="CDF", max_length=3, verbose_name="Devise"),
        ),
    ]
