# Generated by Django 6.0 on 2026-01-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0023_alter_payment_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Bibliothèque Numérique Calures", max_length=255
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Téléversez le logo du site ici.",
                        null=True,
                        upload_to="site_branding/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration du Site",
                "verbose_name_plural": "Configuration du Site",
            },
        ),
    ]
