# Generated by Django 6.0 on 2026-01-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0024_siteconfiguration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteconfiguration",
            options={
                "verbose_name": "Personnalisation du Site",
                "verbose_name_plural": "Personnalisation du Site",
            },
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="footer_text",
            field=models.CharField(
                blank=True,
                default="Tous droits réservés.",
                max_length=255,
                verbose_name="Texte du pied de page",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_description",
            field=models.TextField(
                default="Découvrez les publications exclusives de Calures Éditions. Une bibliothèque numérique souveraine offrant des milliers de livres, formations vidéo et podcasts pour l'excellence africaine.",
                help_text="Le texte court sous le titre.",
                verbose_name="Description de l'accueil",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="home_title",
            field=models.CharField(
                default="Apprenez sans limites avec la Bibliothèque Numérique Calures",
                help_text="Le grand titre affiché sur la page d'accueil.",
                max_length=255,
                verbose_name="Titre de l'accueil",
            ),
        ),
    ]
