# Generated by Django 5.0.7 on 2026-01-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0025_alter_siteconfiguration_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="books",
                through="catalogue.AuthorBook",
                to="catalogue.author",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="libraries",
            field=models.ManyToManyField(
                blank=True,
                related_name="books",
                through="catalogue.LibraryBook",
                to="catalogue.library",
            ),
        ),
    ]
