# Generated by Django 5.0.7 on 2026-01-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0026_alter_book_authors_alter_book_libraries"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="about_text",
            field=models.TextField(
                blank=True,
                help_text="Le contenu détaillé de la page À propos.",
                verbose_name="Texte de la page À propos",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="about_title",
            field=models.CharField(
                blank=True,
                default="À Propos de Nous",
                max_length=255,
                verbose_name="Titre de la page À propos",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="mission_text",
            field=models.TextField(
                blank=True,
                default="Notre mission est de rendre la connaissance accessible à tous...",
                help_text="Le texte décrivant la mission du site.",
                verbose_name="Texte de mission",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="mission_title",
            field=models.CharField(
                blank=True,
                default="Notre Mission",
                max_length=255,
                verbose_name="Titre de la mission",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Publié"),
        ),
    ]
