# Generated by Django 5.0.7 on 2026-01-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0027_siteconfiguration_about_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="text_of_the_week",
            field=models.TextField(
                default="L'éducation est l'arme la plus puissante qu'on puisse utiliser pour changer le monde.",
                help_text="Le texte affiché dans la barre de navigation.",
                verbose_name="Texte de la semaine",
            ),
        ),
    ]
