# Generated by Django 5.0.7 on 2026-03-21 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0028_siteconfiguration_text_of_the_week"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="free_pages_count",
            field=models.PositiveIntegerField(
                default=15,
                help_text="Nombre de pages accessibles gratuitement (0 = aucune preview)",
                verbose_name="Nombre de pages libres",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(
                choices=[
                    ("articles", "Articles"),
                    ("magasin", "Magasin"),
                    ("revues_scientifiques", "Revues Scientifiques"),
                    ("geographie_histoires", "Géographie et Histoires"),
                    ("theories_litteraires", "Théories Littéraires"),
                    ("tourisme", "Tourisme"),
                    ("hotellerie", "Hôtellerie"),
                    ("sport", "Sport"),
                    ("loisir", "Loisir"),
                    ("dev_personnel", "Développement Personnel"),
                    ("fiction", "Fiction"),
                    ("non_fiction", "Non-fiction"),
                    ("science", "Science"),
                    ("biography", "Biographie"),
                    ("poetry", "Poésie"),
                    ("other", "Autre"),
                ],
                default="other",
                max_length=50,
                verbose_name="Genre",
            ),
        ),
        migrations.CreateModel(
            name="PrintOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Nom complet"),
                ),
                ("phone", models.CharField(max_length=30, verbose_name="Téléphone")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("city", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmée"),
                            ("shipped", "Expédiée"),
                            ("delivered", "Livrée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_orders",
                        to="catalogue.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande imprimée",
                "verbose_name_plural": "Commandes imprimées",
                "ordering": ["-created_at"],
            },
        ),
    ]
