# Generated by Django 5.0.7 on 2026-03-21 21:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0029_alter_book_free_pages_count_alter_book_genre_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donateur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Message (optionnel)"
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Montant (FC)",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, verbose_name="Visible publiquement"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Donateur",
                "verbose_name_plural": "Donateurs",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LienSocial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("youtube", "YouTube"),
                            ("whatsapp", "WhatsApp"),
                            ("tiktok", "TikTok"),
                            ("twitter", "X (Twitter)"),
                            ("linkedin", "LinkedIn"),
                            ("email", "Email"),
                            ("telegram", "Telegram"),
                            ("instagram", "Instagram"),
                        ],
                        max_length=20,
                        verbose_name="Plateforme",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Ex: +243 812 345 678, @bnccalures, contact@bnc.com",
                        max_length=100,
                        verbose_name="Libellé affiché",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="URL complète ou mailto: ou tel:",
                        max_length=500,
                        verbose_name="Lien / URL",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
            ],
            options={
                "verbose_name": "Lien social",
                "verbose_name_plural": "Liens sociaux",
                "ordering": ["order"],
            },
        ),
    ]
