# Generated by Django 5.0.7 on 2026-03-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0030_donateur_liensocial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Carte de crédit"),
                    ("paypal", "PayPal"),
                    ("mobile_money", "Mobile Money"),
                    ("card", "Carte bancaire"),
                    ("airtel_money", "Airtel Money"),
                    ("mpesa", "M-Pesa"),
                    ("orange_money", "Orange Money RDC"),
                    ("bank_transfer", "Virement bancaire"),
                    ("moneroo", "Moneroo"),
                    ("other", "Autre"),
                ],
                default="credit_card",
                max_length=50,
                verbose_name="Méthode de paiement",
            ),
        ),
    ]
