# Generated by Django 5.0.7 on 2026-03-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0031_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="donateur",
            name="contact",
            field=models.CharField(
                blank=True,
                help_text="Numéro de téléphone ou email du donateur",
                max_length=200,
                verbose_name="Contact (téléphone ou email)",
            ),
        ),
        migrations.AddField(
            model_name="donateur",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("completed", "Complété"),
                    ("failed", "Échoué"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Statut du paiement",
            ),
        ),
        migrations.AddField(
            model_name="donateur",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Référence unique du paiement Moneroo",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="ID de transaction",
            ),
        ),
    ]
