# Generated by Django 5.0.7 on 2026-03-30 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0032_donateur_contact_donateur_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=280, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Court résumé affiché dans les listes",
                        max_length=500,
                        verbose_name="Extrait",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Contenu complet de l'article", verbose_name="Contenu"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="articles/%Y/%m/",
                        verbose_name="Image de couverture",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LITTERATURE", "Littérature"),
                            ("CULTURE", "Culture"),
                            ("EDITION", "Édition"),
                            ("AUTEUR", "Portrait d'auteur"),
                            ("EVENEMENT", "Événement"),
                            ("SOCIETE", "Société"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True,
                        default="Calures Éditions",
                        max_length=150,
                        verbose_name="Auteur de l'article",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Affiché en priorité sur la page d'accueil",
                        verbose_name="À la une",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de vues"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de publication"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "-created_at"],
                        name="catalogue_a_is_publ_4b61d3_idx",
                    ),
                    models.Index(
                        fields=["category"], name="catalogue_a_categor_de0289_idx"
                    ),
                    models.Index(fields=["slug"], name="catalogue_a_slug_d3a226_idx"),
                ],
            },
        ),
    ]
