# Generated by Django 5.0.7 on 2026-03-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0033_add_article_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="event_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date et heure si l'article est lié à un événement",
                null=True,
                verbose_name="Date de l'événement",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="event_end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date et heure de fin (optionnel)",
                null=True,
                verbose_name="Date de fin",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="event_location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Lieu de l'événement (optionnel)",
                max_length=255,
                verbose_name="Lieu",
            ),
        ),
    ]
