# Generated by Django 5.0.7 on 2026-06-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0034_article_event_date_article_event_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="facebook_url",
            field=models.URLField(blank=True, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="author",
            name="instagram_url",
            field=models.URLField(blank=True, verbose_name="Instagram"),
        ),
        migrations.AddField(
            model_name="author",
            name="linkedin_url",
            field=models.URLField(blank=True, verbose_name="LinkedIn"),
        ),
        migrations.AddField(
            model_name="author",
            name="tiktok_url",
            field=models.URLField(blank=True, verbose_name="TikTok"),
        ),
        migrations.AddField(
            model_name="author",
            name="x_url",
            field=models.URLField(blank=True, verbose_name="X (Twitter)"),
        ),
        migrations.AddField(
            model_name="author",
            name="youtube_url",
            field=models.URLField(blank=True, verbose_name="YouTube"),
        ),
    ]
