# Generated by Django 5.0.7 on 2026-06-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0035_author_social_links_and_photo_admin_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="pwa_logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo de l'application installable (PWA). Recommandé: image carrée 512x512.",
                null=True,
                upload_to="site_branding/",
            ),
        ),
    ]
